name: Run E2E tests
on:
  push:
jobs:
  trafficlight:
    name: E2E tests run on element call
    services:
      adapter1:
        image: ghcr.io/vector-im/trafficlight-adapter-element-call:main
        env:
          BASE_APP_URL: https://call.element.io
          TRAFFICLIGHT_URL: http://trafficlight:5000
        options: "--restart always"
      adapter2:
        image: ghcr.io/vector-im/trafficlight-adapter-element-call:main
        env:
          BASE_APP_URL: https://call.element.io
          TRAFFICLIGHT_URL: http://trafficlight:5000
        options: "--restart always"
    runs-on: ubuntu-latest
    container:
        image: trafficlight-tests
        volumes:
          - $HOME/trafficlight-instance/:/app/instance/
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: trafficlight
          file: "Dockerfile"
          tags: "ec-trafficlight:latest"
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - name: run trafficlight
        uses: ec-trafficlight:latest
